export const products_1 = [
  {
    id: 200179,
    parent_id: 200178,
    sku: "138729",
    name: "Penduline Kids Air Freshener Fruity Fun 400 ml",
    name_en: "Penduline Kids Air Freshener Fruity Fun 400 ml",
    name_ar: "بندولين معطر جو للأطفال - فروتى فان 400 مل",
    encoded_name_en:
      "Penduline%20Kids%20Air%20Freshener%20Fruity%20Fun%20400%20ml",
    encoded_name_ar:
      "%D8%A8%D9%86%D8%AF%D9%88%D9%84%D9%8A%D9%86%20%D9%85%D8%B9%D8%B7%D8%B1%20%D8%AC%D9%88%20%D9%84%D9%84%D8%A3%D8%B7%D9%81%D8%A7%D9%84%20-%20%D9%81%D8%B1%D9%88%D8%AA%D9%89%20%D9%81%D8%A7%D9%86%20400%20%D9%85%D9%84",
    featured: false,
    preorder: false,
    preorder_start_date: null,
    preorder_end_date: null,
    discount_start_date: null,
    discount_end_date: null,
    discount_max_per_period: null,
    discount_period_cycle_days: null,
    direct_discount: false,
    category: {
      id: 1112,
      name: "DAILY ESSENTIALS",
      name_ar: "العناية اليومية",
      slug: "daily-essentials",
      slug_ar: "",
      sub_categories: [
        {
          id: 1143,
          name: "AIR FRESHENERS",
          name_ar: "معطرات الجو",
          slug: "air-fresheners",
          slug_ar: null,
        },
      ],
    },
    optional_category: null,
    in_stock: false,
    stock: 0,
    rate: "5.00",
    rate_count: 0,
    promotion: null,
    promotion_en: null,
    promotion_ar: null,
    is_favourite: false,
    is_compare: false,
    brand: {
      id: 8757,
      name: "Penduline",
      name_ar: "بندولين",
      name_en: null,
      image:
        "https://cdn.supercommerce.io/tarshouby/uploads/Penduline-1655399609.jpg",
      slug: "penduline-1684311575",
      slug_ar: null,
    },
    payment_methods_discount_name_en: null,
    payment_methods_discount_name_ar: null,
    promos: [],
    product_variants_options: [],
    product_variants: [
      {
        id: 200179,
        name: "Penduline Kids Air Freshener Fruity Fun 400 ml",
        name_en: "Penduline Kids Air Freshener Fruity Fun 400 ml",
        name_ar: "بندولين معطر جو للأطفال - فروتى فان 400 مل",
        sku: "138729",
        slug: "penduline-kids-air-fresh-fruity-fun400ml-1777562224",
        slug_ar: null,
        price: 110,
        discount_price: null,
        stock: 0,
        stock_alert: null,
        options: [],
        preorder: false,
        preorder_price: 0,
        value_ids: [],
        image:
          "https://cdn.supercommerce.io/tarshouby/uploads/138729-1763229790.jpg",
        alt: "Penduline Kids Air Freshener Fruity Fun 400 ml",
        alt_ar: "بندولين معطر جو للأطفال - فروتى فان 400 مل",
        parent_id: 200178,
        images: [],
        in_stock: false,
        active: true,
        free_delivery: false,
        cart_step: 1,
        min_per_order: 0,
        promotion: null,
        promotion_en: null,
        promotion_ar: null,
        special_labels: null,
        special_labels_ar: null,
        special_labels_color: null,
        need_prescription: 0,
        step_unit_label_en: "Unit",
        step_unit_label_ar: "وحدة",
        step_package_label_en: "Package",
        step_package_label_ar: "علبة",
        enable_step_package: 0,
      },
    ],
    product_variants_count: 0,
    order: null,
    active: true,
    amount: 0,
    can_buy: null,
    soft_deleted: false,
    commission_amount: 0,
    affiliate_commission: null,
    variant_max_price: 0,
    exclusive_price: null,
    slug: "penduline-kids-air-fresh-fruity-fun400ml-1777562224",
    slug_ar: null,
    share_link:
      "https://alabdellatif-tarshouby.com/en/penduline-kids-air-fresh-fruity-fun400ml-1777562224",
    image:
      "https://cdn.supercommerce.io/tarshouby/uploads/138729-1763229790.jpg",
    alt: "Penduline Kids Air Freshener Fruity Fun 400 ml",
    alt_ar: "بندولين معطر جو للأطفال - فروتى فان 400 مل",
    images: [],
    min_per_order: 0,
    max_per_order: null,
    type: 1,
    available_soon: false,
    price: 110,
    discount_price: null,
    preorder_price: 0,
    weight: "1.00",
    special_labels: null,
    special_labels_ar: null,
    special_labels_color: null,
    need_prescription: 0,
  },
  {
    id: 199993,
    parent_id: 199992,
    sku: "138666",
    name: "Eco Bel Hair Leave-In 250 ml",
    name_en: "Eco Bel Hair Leave-In 250 ml",
    name_ar: "إيكوبيل ليف-إن للشعر 250 مل",
    encoded_name_en: "Eco%20Bel%20Hair%20Leave-In%20250%20ml",
    encoded_name_ar:
      "%D8%A5%D9%8A%D9%83%D9%88%D8%A8%D9%8A%D9%84%20%D9%84%D9%8A%D9%81-%D8%A5%D9%86%20%D9%84%D9%84%D8%B4%D8%B9%D8%B1%20250%20%D9%85%D9%84",
    featured: false,
    preorder: false,
    preorder_start_date: null,
    preorder_end_date: null,
    discount_start_date: null,
    discount_end_date: null,
    discount_max_per_period: null,
    discount_period_cycle_days: null,
    direct_discount: false,
    category: {
      id: 1185,
      name: "HAIR CARE",
      name_ar: "العناية بالشعر",
      slug: "hair-care",
      slug_ar: "",
      sub_categories: [
        {
          id: 1215,
          name: "LEAVE IN",
          name_ar: "بلسم ليف إن",
          slug: "leave-in",
          slug_ar: null,
        },
      ],
    },
    optional_category: null,
    in_stock: false,
    stock: 0,
    rate: "5.00",
    rate_count: 0,
    promotion: null,
    promotion_en: null,
    promotion_ar: null,
    is_favourite: false,
    is_compare: false,
    brand: {
      id: 9367,
      name: "Eco Bel",
      name_ar: "إيكوبيل",
      name_en: null,
      image:
        "https://cdn.supercommerce.io/tarshouby/uploads/eco-1762859040.png",
      slug: "eco bel",
      slug_ar: "إيكوبيل",
    },
    payment_methods_discount_name_en: null,
    payment_methods_discount_name_ar: null,
    promos: [],
    product_variants_options: [],
    product_variants: [
      {
        id: 199993,
        name: "Eco Bel Hair Leave-In 250 ml",
        name_en: "Eco Bel Hair Leave-In 250 ml",
        name_ar: "إيكوبيل ليف-إن للشعر 250 مل",
        sku: "138666",
        slug: "eco-bel-hair-leave-in-250ml-1777562219",
        slug_ar: null,
        price: 250,
        discount_price: null,
        stock: 0,
        stock_alert: null,
        options: [],
        preorder: false,
        preorder_price: 0,
        value_ids: [],
        image:
          "https://cdn.supercommerce.io/tarshouby/uploads/138666-1762871235.jpg",
        alt: null,
        alt_ar: null,
        parent_id: 199992,
        images: [],
        in_stock: false,
        active: true,
        free_delivery: false,
        cart_step: 1,
        min_per_order: 0,
        promotion: null,
        promotion_en: null,
        promotion_ar: null,
        special_labels: null,
        special_labels_ar: null,
        special_labels_color: null,
        need_prescription: 0,
        step_unit_label_en: "Unit",
        step_unit_label_ar: "وحدة",
        step_package_label_en: "Package",
        step_package_label_ar: "علبة",
        enable_step_package: 0,
      },
    ],
    product_variants_count: 0,
    order: null,
    active: true,
    amount: 0,
    can_buy: null,
    soft_deleted: false,
    commission_amount: 0,
    affiliate_commission: null,
    variant_max_price: 0,
    exclusive_price: null,
    slug: "eco-bel-hair-leave-in-250ml-1777562219",
    slug_ar: null,
    share_link:
      "https://alabdellatif-tarshouby.com/en/eco-bel-hair-leave-in-250ml-1777562219",
    image:
      "https://cdn.supercommerce.io/tarshouby/uploads/138666-1762871235.jpg",
    alt: null,
    alt_ar: null,
    images: [],
    min_per_order: 0,
    max_per_order: null,
    type: 1,
    available_soon: false,
    price: 250,
    discount_price: null,
    preorder_price: 0,
    weight: "1.00",
    special_labels: null,
    special_labels_ar: null,
    special_labels_color: null,
    need_prescription: 0,
  },
  {
    id: 199989,
    parent_id: 199988,
    sku: "138664",
    name: "Eco Bel Hair Mask 500 ml",
    name_en: "Eco Bel Hair Mask 500 ml",
    name_ar: "إيكوبيل ماسك للشعر 500 مل",
    encoded_name_en: "Eco%20Bel%20Hair%20Mask%20500%20ml",
    encoded_name_ar:
      "%D8%A5%D9%8A%D9%83%D9%88%D8%A8%D9%8A%D9%84%20%D9%85%D8%A7%D8%B3%D9%83%20%D9%84%D9%84%D8%B4%D8%B9%D8%B1%20500%20%D9%85%D9%84",
    featured: false,
    preorder: false,
    preorder_start_date: null,
    preorder_end_date: null,
    discount_start_date: null,
    discount_end_date: null,
    discount_max_per_period: null,
    discount_period_cycle_days: null,
    direct_discount: false,
    category: {
      id: 1185,
      name: "HAIR CARE",
      name_ar: "العناية بالشعر",
      slug: "hair-care",
      slug_ar: "",
      sub_categories: [
        {
          id: 1461,
          name: "HAIR MASK",
          name_ar: "حمام كريم للشعر",
          slug: "hair-mask",
          slug_ar: null,
        },
      ],
    },
    optional_category: null,
    in_stock: false,
    stock: 0,
    rate: "5.00",
    rate_count: 0,
    promotion: null,
    promotion_en: null,
    promotion_ar: null,
    is_favourite: false,
    is_compare: false,
    brand: {
      id: 9367,
      name: "Eco Bel",
      name_ar: "إيكوبيل",
      name_en: null,
      image:
        "https://cdn.supercommerce.io/tarshouby/uploads/eco-1762859040.png",
      slug: "eco bel",
      slug_ar: "إيكوبيل",
    },
    payment_methods_discount_name_en: null,
    payment_methods_discount_name_ar: null,
    promos: [],
    product_variants_options: [],
    product_variants: [
      {
        id: 199989,
        name: "Eco Bel Hair Mask 500 ml",
        name_en: "Eco Bel Hair Mask 500 ml",
        name_ar: "إيكوبيل ماسك للشعر 500 مل",
        sku: "138664",
        slug: "eco-bel-hair-mask-drydamage500ml-1777562219",
        slug_ar: null,
        price: 250,
        discount_price: null,
        stock: 0,
        stock_alert: null,
        options: [],
        preorder: false,
        preorder_price: 0,
        value_ids: [],
        image:
          "https://cdn.supercommerce.io/tarshouby/uploads/138664-1762869704.jpg",
        alt: null,
        alt_ar: null,
        parent_id: 199988,
        images: [],
        in_stock: false,
        active: true,
        free_delivery: false,
        cart_step: 1,
        min_per_order: 0,
        promotion: null,
        promotion_en: null,
        promotion_ar: null,
        special_labels: null,
        special_labels_ar: null,
        special_labels_color: null,
        need_prescription: 0,
        step_unit_label_en: "Unit",
        step_unit_label_ar: "وحدة",
        step_package_label_en: "Package",
        step_package_label_ar: "علبة",
        enable_step_package: 0,
      },
    ],
    product_variants_count: 0,
    order: null,
    active: true,
    amount: 0,
    can_buy: null,
    soft_deleted: false,
    commission_amount: 0,
    affiliate_commission: null,
    variant_max_price: 0,
    exclusive_price: null,
    slug: "eco-bel-hair-mask-drydamage500ml-1777562219",
    slug_ar: null,
    share_link:
      "https://alabdellatif-tarshouby.com/en/eco-bel-hair-mask-drydamage500ml-1777562219",
    image:
      "https://cdn.supercommerce.io/tarshouby/uploads/138664-1762869704.jpg",
    alt: null,
    alt_ar: null,
    images: [],
    min_per_order: 0,
    max_per_order: null,
    type: 1,
    available_soon: false,
    price: 250,
    discount_price: null,
    preorder_price: 0,
    weight: "1.00",
    special_labels: null,
    special_labels_ar: null,
    special_labels_color: null,
    need_prescription: 0,
  },
  {
    id: 199985,
    parent_id: 199984,
    sku: "138662",
    name: "Eco Bel Whitenning Body Milk Lotion 250 ml",
    name_en: "Eco Bel Whitenning Body Milk Lotion 250 ml",
    name_ar: "إيكوبيل لوشن تفتيح للجسم 250 مل",
    encoded_name_en: "Eco%20Bel%20Whitenning%20Body%20Milk%20Lotion%20250%20ml",
    encoded_name_ar:
      "%D8%A5%D9%8A%D9%83%D9%88%D8%A8%D9%8A%D9%84%20%D9%84%D9%88%D8%B4%D9%86%20%D8%AA%D9%81%D8%AA%D9%8A%D8%AD%20%D9%84%D9%84%D8%AC%D8%B3%D9%85%20250%20%D9%85%D9%84",
    featured: false,
    preorder: false,
    preorder_start_date: null,
    preorder_end_date: null,
    discount_start_date: null,
    discount_end_date: null,
    discount_max_per_period: null,
    discount_period_cycle_days: null,
    direct_discount: false,
    category: {
      id: 1149,
      name: "SKIN CARE",
      name_ar: "العناية بالبشرة والجسم",
      slug: "skin-care",
      slug_ar: "",
      sub_categories: [
        {
          id: 1164,
          name: "BODY MOISTURIZERS",
          name_ar: "مرطب للجسم",
          slug: "body-moisturizers",
          slug_ar: null,
        },
      ],
    },
    optional_category: {
      id: 1149,
      name: "SKIN CARE",
      name_ar: "العناية بالبشرة والجسم",
      slug: "skin-care",
      slug_ar: "",
      sub_categories: [
        {
          id: 1163,
          name: "BODY WHITENING",
          name_ar: "تفتيح الجسم",
          slug: "body-whitening",
          slug_ar: null,
        },
      ],
    },
    in_stock: false,
    stock: 0,
    rate: "5.00",
    rate_count: 0,
    promotion: null,
    promotion_en: null,
    promotion_ar: null,
    is_favourite: false,
    is_compare: false,
    brand: {
      id: 9367,
      name: "Eco Bel",
      name_ar: "إيكوبيل",
      name_en: null,
      image:
        "https://cdn.supercommerce.io/tarshouby/uploads/eco-1762859040.png",
      slug: "eco bel",
      slug_ar: "إيكوبيل",
    },
    payment_methods_discount_name_en: null,
    payment_methods_discount_name_ar: null,
    promos: [],
    product_variants_options: [],
    product_variants: [
      {
        id: 199985,
        name: "Eco Bel Whitenning Body Milk Lotion 250 ml",
        name_en: "Eco Bel Whitenning Body Milk Lotion 250 ml",
        name_ar: "إيكوبيل لوشن تفتيح للجسم 250 مل",
        sku: "138662",
        slug: "eco-bel-white-body-milk-lotion250mlgmyaa-anoaaa-albshr-1777562219",
        slug_ar: null,
        price: 250,
        discount_price: null,
        stock: 0,
        stock_alert: null,
        options: [],
        preorder: false,
        preorder_price: 0,
        value_ids: [],
        image:
          "https://cdn.supercommerce.io/tarshouby/uploads/138662-1762866790.jpg",
        alt: null,
        alt_ar: null,
        parent_id: 199984,
        images: [],
        in_stock: false,
        active: true,
        free_delivery: false,
        cart_step: 1,
        min_per_order: 0,
        promotion: null,
        promotion_en: null,
        promotion_ar: null,
        special_labels: null,
        special_labels_ar: null,
        special_labels_color: null,
        need_prescription: 0,
        step_unit_label_en: "Unit",
        step_unit_label_ar: "وحدة",
        step_package_label_en: "Package",
        step_package_label_ar: "علبة",
        enable_step_package: 0,
      },
    ],
    product_variants_count: 0,
    order: null,
    active: true,
    amount: 0,
    can_buy: null,
    soft_deleted: false,
    commission_amount: 0,
    affiliate_commission: null,
    variant_max_price: 0,
    exclusive_price: null,
    slug: "eco-bel-white-body-milk-lotion250mlgmyaa-anoaaa-albshr-1777562219",
    slug_ar: null,
    share_link:
      "https://alabdellatif-tarshouby.com/en/eco-bel-white-body-milk-lotion250mlgmyaa-anoaaa-albshr-1777562219",
    image:
      "https://cdn.supercommerce.io/tarshouby/uploads/138662-1762866790.jpg",
    alt: null,
    alt_ar: null,
    images: [],
    min_per_order: 0,
    max_per_order: 1,
    type: 1,
    available_soon: false,
    price: 250,
    discount_price: null,
    preorder_price: 0,
    weight: "1.00",
    special_labels: null,
    special_labels_ar: null,
    special_labels_color: null,
    need_prescription: 0,
  },
  {
    id: 199947,
    parent_id: 199946,
    sku: "138556",
    name: "Sensodyne Cavity & Sensitivity Toothpaste 50 ml",
    name_en: "Sensodyne Cavity & Sensitivity Toothpaste 50 ml",
    name_ar: "سنسوداين معجون أسنان مكافح التسوس 50 مل",
    encoded_name_en:
      "Sensodyne%20Cavity%20%26%20Sensitivity%20Toothpaste%2050%20ml",
    encoded_name_ar:
      "%D8%B3%D9%86%D8%B3%D9%88%D8%AF%D8%A7%D9%8A%D9%86%20%D9%85%D8%B9%D8%AC%D9%88%D9%86%20%D8%A3%D8%B3%D9%86%D8%A7%D9%86%20%D9%85%D9%83%D8%A7%D9%81%D8%AD%20%D8%A7%D9%84%D8%AA%D8%B3%D9%88%D8%B3%2050%20%D9%85%D9%84",
    featured: false,
    preorder: false,
    preorder_start_date: null,
    preorder_end_date: null,
    discount_start_date: null,
    discount_end_date: null,
    discount_max_per_period: null,
    discount_period_cycle_days: null,
    direct_discount: false,
    category: {
      id: 1112,
      name: "DAILY ESSENTIALS",
      name_ar: "العناية اليومية",
      slug: "daily-essentials",
      slug_ar: "",
      sub_categories: [
        {
          id: 1133,
          name: "TOOTHPASTE",
          name_ar: "معجون الأسنان",
          slug: "toothpaste",
          slug_ar: null,
        },
      ],
    },
    optional_category: null,
    in_stock: false,
    stock: 0,
    rate: "5.00",
    rate_count: 0,
    promotion: null,
    promotion_en: null,
    promotion_ar: null,
    is_favourite: false,
    is_compare: false,
    brand: {
      id: 9028,
      name: "Sensodyne",
      name_ar: "سنسوداين",
      name_en: null,
      image:
        "https://cdn.supercommerce.io/tarshouby/uploads/Sensodyne-1703102297.jpg",
      slug: "sensodyne-1684311578",
      slug_ar: null,
    },
    payment_methods_discount_name_en: null,
    payment_methods_discount_name_ar: null,
    promos: [],
    product_variants_options: [],
    product_variants: [
      {
        id: 199947,
        name: "Sensodyne Cavity & Sensitivity Toothpaste 50 ml",
        name_en: "Sensodyne Cavity & Sensitivity Toothpaste 50 ml",
        name_ar: "سنسوداين معجون أسنان مكافح التسوس 50 مل",
        sku: "138556",
        slug: "sensodyne-tooth-paste-cavitysensitivity50mlgsk-ha-mkafh-altsos-oalasnan-alhsas-b",
        slug_ar: null,
        price: 55,
        discount_price: null,
        stock: 0,
        stock_alert: null,
        options: [],
        preorder: false,
        preorder_price: 0,
        value_ids: [],
        image:
          "https://cdn.supercommerce.io/tarshouby/uploads/138556-1762964540.jpg",
        alt: "Sensodyne Cavity & Sensitivity Toothpaste 50 ml",
        alt_ar: "سنسوداين معجون أسنان مكافح التسوس 50 مل",
        parent_id: 199946,
        images: [],
        in_stock: false,
        active: true,
        free_delivery: false,
        cart_step: 1,
        min_per_order: 0,
        promotion: null,
        promotion_en: null,
        promotion_ar: null,
        special_labels: null,
        special_labels_ar: null,
        special_labels_color: null,
        need_prescription: 0,
        step_unit_label_en: "Unit",
        step_unit_label_ar: "وحدة",
        step_package_label_en: "Package",
        step_package_label_ar: "علبة",
        enable_step_package: 0,
      },
    ],
    product_variants_count: 0,
    order: null,
    active: true,
    amount: 0,
    can_buy: null,
    soft_deleted: false,
    commission_amount: 0,
    affiliate_commission: null,
    variant_max_price: 0,
    exclusive_price: null,
    slug: "sensodyne-tooth-paste-cavitysensitivity50mlgsk-ha-mkafh-altsos-oalasnan-alhsas-b",
    slug_ar: null,
    share_link:
      "https://alabdellatif-tarshouby.com/en/sensodyne-tooth-paste-cavitysensitivity50mlgsk-ha-mkafh-altsos-oalasnan-alhsas-b",
    image:
      "https://cdn.supercommerce.io/tarshouby/uploads/138556-1762964540.jpg",
    alt: "Sensodyne Cavity & Sensitivity Toothpaste 50 ml",
    alt_ar: "سنسوداين معجون أسنان مكافح التسوس 50 مل",
    images: [],
    min_per_order: 0,
    max_per_order: 1,
    type: 1,
    available_soon: false,
    price: 55,
    discount_price: null,
    preorder_price: 0,
    weight: "1.00",
    special_labels: null,
    special_labels_ar: null,
    special_labels_color: null,
    need_prescription: 0,
  },
  {
    id: 199939,
    parent_id: 199938,
    sku: "138545",
    name: "Pantene Goodbye Frizz Repair Oil Replacement 275 ml",
    name_en: "Pantene Goodbye Frizz Repair Oil Replacement 275 ml",
    name_ar: "بانتين بديل الزيت وداعًا لتطايرات 275 مل",
    encoded_name_en:
      "Pantene%20Goodbye%20Frizz%20Repair%20Oil%20Replacement%20275%20ml",
    encoded_name_ar:
      "%D8%A8%D8%A7%D9%86%D8%AA%D9%8A%D9%86%20%D8%A8%D8%AF%D9%8A%D9%84%20%D8%A7%D9%84%D8%B2%D9%8A%D8%AA%20%D9%88%D8%AF%D8%A7%D8%B9%D9%8B%D8%A7%20%D9%84%D8%AA%D8%B7%D8%A7%D9%8A%D8%B1%D8%A7%D8%AA%20275%20%D9%85%D9%84",
    featured: false,
    preorder: false,
    preorder_start_date: null,
    preorder_end_date: null,
    discount_start_date: null,
    discount_end_date: null,
    discount_max_per_period: null,
    discount_period_cycle_days: null,
    direct_discount: false,
    category: {
      id: 1185,
      name: "HAIR CARE",
      name_ar: "العناية بالشعر",
      slug: "hair-care",
      slug_ar: "",
      sub_categories: [
        {
          id: 1219,
          name: "OIL REPLACEMENTS",
          name_ar: "بديل الزيت",
          slug: "oil-replacements",
          slug_ar: null,
        },
      ],
    },
    optional_category: null,
    in_stock: false,
    stock: 0,
    rate: "5.00",
    rate_count: 0,
    promotion: null,
    promotion_en: null,
    promotion_ar: null,
    is_favourite: false,
    is_compare: false,
    brand: {
      id: 8900,
      name: "Pantene",
      name_ar: "بانتين",
      name_en: null,
      image:
        "https://cdn.supercommerce.io/tarshouby/uploads/Pantene-1703100518.jpg",
      slug: "pantene-1684311577",
      slug_ar: null,
    },
    payment_methods_discount_name_en: null,
    payment_methods_discount_name_ar: null,
    promos: [],
    product_variants_options: [],
    product_variants: [
      {
        id: 199939,
        name: "Pantene Goodbye Frizz Repair Oil Replacement 275 ml",
        name_en: "Pantene Goodbye Frizz Repair Oil Replacement 275 ml",
        name_ar: "بانتين بديل الزيت وداعًا لتطايرات 275 مل",
        sku: "138545",
        slug: "pantene-hair-oil-good-bye-frizz-275mlllthkm-fy-ttayr-alshaar-1777562205",
        slug_ar: null,
        price: 210,
        discount_price: null,
        stock: 0,
        stock_alert: null,
        options: [],
        preorder: false,
        preorder_price: 0,
        value_ids: [],
        image:
          "https://cdn.supercommerce.io/tarshouby/uploads/138545-1762966338.jpg",
        alt: "Pantene Goodbye Frizz Repair Oil Replacement 275 ml",
        alt_ar: "بانتين بديل الزيت وداعًا لتطايرات 275 مل",
        parent_id: 199938,
        images: [],
        in_stock: false,
        active: true,
        free_delivery: false,
        cart_step: 1,
        min_per_order: 0,
        promotion: null,
        promotion_en: null,
        promotion_ar: null,
        special_labels: null,
        special_labels_ar: null,
        special_labels_color: null,
        need_prescription: 0,
        step_unit_label_en: "Unit",
        step_unit_label_ar: "وحدة",
        step_package_label_en: "Package",
        step_package_label_ar: "علبة",
        enable_step_package: 0,
      },
    ],
    product_variants_count: 0,
    order: null,
    active: true,
    amount: 0,
    can_buy: null,
    soft_deleted: false,
    commission_amount: 0,
    affiliate_commission: null,
    variant_max_price: 0,
    exclusive_price: null,
    slug: "pantene-hair-oil-good-bye-frizz-275mlllthkm-fy-ttayr-alshaar-1777562205",
    slug_ar: null,
    share_link:
      "https://alabdellatif-tarshouby.com/en/pantene-hair-oil-good-bye-frizz-275mlllthkm-fy-ttayr-alshaar-1777562205",
    image:
      "https://cdn.supercommerce.io/tarshouby/uploads/138545-1762966338.jpg",
    alt: "Pantene Goodbye Frizz Repair Oil Replacement 275 ml",
    alt_ar: "بانتين بديل الزيت وداعًا لتطايرات 275 مل",
    images: [],
    min_per_order: 0,
    max_per_order: null,
    type: 1,
    available_soon: false,
    price: 210,
    discount_price: null,
    preorder_price: 0,
    weight: "1.00",
    special_labels: null,
    special_labels_ar: null,
    special_labels_color: null,
    need_prescription: 0,
  },
  {
    id: 199937,
    parent_id: 199936,
    sku: "138544",
    name: "Pantene Milky Damage Repair Oil Replacement 180 ML",
    name_en: "Pantene Milky Damage Repair Oil Replacement 180 ML",
    name_ar: "بانتين بديل زيت ميلكي لعلاج التلف 180 مل",
    encoded_name_en:
      "Pantene%20Milky%20Damage%20Repair%20Oil%20Replacement%20180%20ML",
    encoded_name_ar:
      "%D8%A8%D8%A7%D9%86%D8%AA%D9%8A%D9%86%20%D8%A8%D8%AF%D9%8A%D9%84%20%D8%B2%D9%8A%D8%AA%20%D9%85%D9%8A%D9%84%D9%83%D9%8A%20%D9%84%D8%B9%D9%84%D8%A7%D8%AC%20%D8%A7%D9%84%D8%AA%D9%84%D9%81%20180%20%D9%85%D9%84",
    featured: false,
    preorder: false,
    preorder_start_date: null,
    preorder_end_date: null,
    discount_start_date: null,
    discount_end_date: null,
    discount_max_per_period: null,
    discount_period_cycle_days: null,
    direct_discount: false,
    category: {
      id: 1185,
      name: "HAIR CARE",
      name_ar: "العناية بالشعر",
      slug: "hair-care",
      slug_ar: "",
      sub_categories: [
        {
          id: 1219,
          name: "OIL REPLACEMENTS",
          name_ar: "بديل الزيت",
          slug: "oil-replacements",
          slug_ar: null,
        },
      ],
    },
    optional_category: null,
    in_stock: false,
    stock: 0,
    rate: "5.00",
    rate_count: 0,
    promotion: null,
    promotion_en: null,
    promotion_ar: null,
    is_favourite: false,
    is_compare: false,
    brand: {
      id: 8900,
      name: "Pantene",
      name_ar: "بانتين",
      name_en: null,
      image:
        "https://cdn.supercommerce.io/tarshouby/uploads/Pantene-1703100518.jpg",
      slug: "pantene-1684311577",
      slug_ar: null,
    },
    payment_methods_discount_name_en: null,
    payment_methods_discount_name_ar: null,
    promos: [],
    product_variants_options: [],
    product_variants: [
      {
        id: 199937,
        name: "Pantene Milky Damage Repair Oil Replacement 180 ML",
        name_en: "Pantene Milky Damage Repair Oil Replacement 180 ML",
        name_ar: "بانتين بديل زيت ميلكي لعلاج التلف 180 مل",
        sku: "138544",
        slug: "pantene-hair-oil-milky-180mlmylk-1777562205",
        slug_ar: null,
        price: 163,
        discount_price: null,
        stock: 0,
        stock_alert: null,
        options: [],
        preorder: false,
        preorder_price: 0,
        value_ids: [],
        image:
          "https://cdn.supercommerce.io/tarshouby/uploads/138544-1762965593.jpg",
        alt: "Pantene Milky Damage Repair Oil Replacement 180 ML",
        alt_ar: "بانتين بديل زيت ميلكي لعلاج التلف 180 مل",
        parent_id: 199936,
        images: [],
        in_stock: false,
        active: true,
        free_delivery: false,
        cart_step: 1,
        min_per_order: 0,
        promotion: null,
        promotion_en: null,
        promotion_ar: null,
        special_labels: null,
        special_labels_ar: null,
        special_labels_color: null,
        need_prescription: 0,
        step_unit_label_en: "Unit",
        step_unit_label_ar: "وحدة",
        step_package_label_en: "Package",
        step_package_label_ar: "علبة",
        enable_step_package: 0,
      },
    ],
    product_variants_count: 0,
    order: null,
    active: true,
    amount: 0,
    can_buy: null,
    soft_deleted: false,
    commission_amount: 0,
    affiliate_commission: null,
    variant_max_price: 0,
    exclusive_price: null,
    slug: "pantene-hair-oil-milky-180mlmylk-1777562205",
    slug_ar: null,
    share_link:
      "https://alabdellatif-tarshouby.com/en/pantene-hair-oil-milky-180mlmylk-1777562205",
    image:
      "https://cdn.supercommerce.io/tarshouby/uploads/138544-1762965593.jpg",
    alt: "Pantene Milky Damage Repair Oil Replacement 180 ML",
    alt_ar: "بانتين بديل زيت ميلكي لعلاج التلف 180 مل",
    images: [],
    min_per_order: 0,
    max_per_order: null,
    type: 1,
    available_soon: false,
    price: 163,
    discount_price: null,
    preorder_price: 0,
    weight: "1.00",
    special_labels: null,
    special_labels_ar: null,
    special_labels_color: null,
    need_prescription: 0,
  },
  {
    id: 199800,
    parent_id: 199799,
    sku: "138519",
    name: "Tecton Hair Mask 250 ml",
    name_en: "Tecton Hair Mask 250 ml",
    name_ar: "تيكتون ماسك للشعر 250 مل",
    encoded_name_en: "Tecton%20Hair%20Mask%20250%20ml",
    encoded_name_ar:
      "%D8%AA%D9%8A%D9%83%D8%AA%D9%88%D9%86%20%D9%85%D8%A7%D8%B3%D9%83%20%D9%84%D9%84%D8%B4%D8%B9%D8%B1%20250%20%D9%85%D9%84",
    featured: false,
    preorder: false,
    preorder_start_date: null,
    preorder_end_date: null,
    discount_start_date: null,
    discount_end_date: null,
    discount_max_per_period: null,
    discount_period_cycle_days: null,
    direct_discount: false,
    category: {
      id: 1185,
      name: "HAIR CARE",
      name_ar: "العناية بالشعر",
      slug: "hair-care",
      slug_ar: "",
      sub_categories: [
        {
          id: 1461,
          name: "HAIR MASK",
          name_ar: "حمام كريم للشعر",
          slug: "hair-mask",
          slug_ar: null,
        },
      ],
    },
    optional_category: null,
    in_stock: false,
    stock: 0,
    rate: "5.00",
    rate_count: 0,
    promotion: null,
    promotion_en: null,
    promotion_ar: null,
    is_favourite: false,
    is_compare: false,
    brand: null,
    payment_methods_discount_name_en: null,
    payment_methods_discount_name_ar: null,
    promos: [],
    product_variants_options: [],
    product_variants: [
      {
        id: 199800,
        name: "Tecton Hair Mask 250 ml",
        name_en: "Tecton Hair Mask 250 ml",
        name_ar: "تيكتون ماسك للشعر 250 مل",
        sku: "138519",
        slug: "tecton-hair-mask5effective250mlmask-ltrtyb-alshaar",
        slug_ar: null,
        price: 350,
        discount_price: null,
        stock: 0,
        stock_alert: null,
        options: [],
        preorder: false,
        preorder_price: 0,
        value_ids: [],
        image:
          "https://cdn.supercommerce.io/tarshouby/uploads/138519-1762433943.jpg",
        alt: "Tecton Hair Mask 250 ml",
        alt_ar: "تيكتون ماسك للشعر 250 مل",
        parent_id: 199799,
        images: [],
        in_stock: false,
        active: true,
        free_delivery: false,
        cart_step: 1,
        min_per_order: 0,
        promotion: null,
        promotion_en: null,
        promotion_ar: null,
        special_labels: null,
        special_labels_ar: null,
        special_labels_color: null,
        need_prescription: 0,
        step_unit_label_en: "Unit",
        step_unit_label_ar: "وحدة",
        step_package_label_en: "Package",
        step_package_label_ar: "علبة",
        enable_step_package: 0,
      },
    ],
    product_variants_count: 0,
    order: null,
    active: true,
    amount: 0,
    can_buy: null,
    soft_deleted: false,
    commission_amount: 0,
    affiliate_commission: null,
    variant_max_price: 0,
    exclusive_price: null,
    slug: "tecton-hair-mask5effective250mlmask-ltrtyb-alshaar",
    slug_ar: null,
    share_link:
      "https://alabdellatif-tarshouby.com/en/tecton-hair-mask5effective250mlmask-ltrtyb-alshaar",
    image:
      "https://cdn.supercommerce.io/tarshouby/uploads/138519-1762433943.jpg",
    alt: "Tecton Hair Mask 250 ml",
    alt_ar: "تيكتون ماسك للشعر 250 مل",
    images: [],
    min_per_order: 0,
    max_per_order: null,
    type: 1,
    available_soon: false,
    price: 350,
    discount_price: null,
    preorder_price: 0,
    weight: "1.00",
    special_labels: null,
    special_labels_ar: null,
    special_labels_color: null,
    need_prescription: 0,
  },
  {
    id: 199792,
    parent_id: 199791,
    sku: "138465",
    name: "Alice (AS205) Brush Original Detangler",
    name_en: "Alice (AS205) Brush Original Detangler",
    name_ar: "أليس (AS205) فرشاة ضد التشابك",
    encoded_name_en: "Alice%20%28AS205%29%20Brush%20Original%20Detangler",
    encoded_name_ar:
      "%D8%A3%D9%84%D9%8A%D8%B3%20%28AS205%29%20%D9%81%D8%B1%D8%B4%D8%A7%D8%A9%20%D8%B6%D8%AF%20%D8%A7%D9%84%D8%AA%D8%B4%D8%A7%D8%A8%D9%83",
    featured: false,
    preorder: false,
    preorder_start_date: null,
    preorder_end_date: null,
    discount_start_date: null,
    discount_end_date: null,
    discount_max_per_period: null,
    discount_period_cycle_days: null,
    direct_discount: false,
    category: {
      id: 1185,
      name: "HAIR CARE",
      name_ar: "العناية بالشعر",
      slug: "hair-care",
      slug_ar: "",
      sub_categories: [
        {
          id: 1226,
          name: "HAIR BRUSHES",
          name_ar: "فرش شعر",
          slug: "hair-brushes",
          slug_ar: null,
        },
      ],
    },
    optional_category: null,
    in_stock: false,
    stock: 0,
    rate: "5.00",
    rate_count: 0,
    promotion: null,
    promotion_en: null,
    promotion_ar: null,
    is_favourite: false,
    is_compare: false,
    brand: {
      id: 9164,
      name: "Alice",
      name_ar: "أليس",
      name_en: null,
      image:
        "https://cdn.supercommerce.io/tarshouby/uploads/ALICE-1701786906.png",
      slug: "alice",
      slug_ar: null,
    },
    payment_methods_discount_name_en: null,
    payment_methods_discount_name_ar: null,
    promos: [],
    product_variants_options: [],
    product_variants: [
      {
        id: 199792,
        name: "Alice (AS205) Brush Original Detangler",
        name_en: "Alice (AS205) Brush Original Detangler",
        name_ar: "أليس (AS205) فرشاة ضد التشابك",
        sku: "138465",
        slug: "alice3322510005brush-originalas205frsha-shaarmof-1777562199",
        slug_ar: null,
        price: 193.9,
        discount_price: null,
        stock: 0,
        stock_alert: null,
        options: [],
        preorder: false,
        preorder_price: 0,
        value_ids: [],
        image:
          "https://cdn.supercommerce.io/tarshouby/uploads/138465-1762450944.jpg",
        alt: "Alice (AS205) Brush Original Detangler",
        alt_ar: "أليس (AS205) فرشاة ضد التشابك",
        parent_id: 199791,
        images: [],
        in_stock: false,
        active: true,
        free_delivery: false,
        cart_step: 1,
        min_per_order: 0,
        promotion: null,
        promotion_en: null,
        promotion_ar: null,
        special_labels: null,
        special_labels_ar: null,
        special_labels_color: null,
        need_prescription: 0,
        step_unit_label_en: "Unit",
        step_unit_label_ar: "وحدة",
        step_package_label_en: "Package",
        step_package_label_ar: "علبة",
        enable_step_package: 0,
      },
    ],
    product_variants_count: 0,
    order: null,
    active: true,
    amount: 0,
    can_buy: null,
    soft_deleted: false,
    commission_amount: 0,
    affiliate_commission: null,
    variant_max_price: 0,
    exclusive_price: null,
    slug: "alice3322510005brush-originalas205frsha-shaarmof-1777562199",
    slug_ar: null,
    share_link:
      "https://alabdellatif-tarshouby.com/en/alice3322510005brush-originalas205frsha-shaarmof-1777562199",
    image:
      "https://cdn.supercommerce.io/tarshouby/uploads/138465-1762450944.jpg",
    alt: "Alice (AS205) Brush Original Detangler",
    alt_ar: "أليس (AS205) فرشاة ضد التشابك",
    images: [],
    min_per_order: 0,
    max_per_order: null,
    type: 1,
    available_soon: false,
    price: 193.9,
    discount_price: null,
    preorder_price: 0,
    weight: "1.00",
    special_labels: null,
    special_labels_ar: null,
    special_labels_color: null,
    need_prescription: 0,
  },
  {
    id: 199782,
    parent_id: 199781,
    sku: "138453",
    name: "Beter (07022)Manicure Nail Clipper (Random Color Choice)",
    name_en: "Beter (07022)Manicure Nail Clipper (Random Color Choice)",
    name_ar: "بيتر(07022) قصافة أظافر (اختيار لون عشوائي)",
    encoded_name_en:
      "Beter%20%2807022%29Manicure%20Nail%20Clipper%20%28Random%20Color%20Choice%29",
    encoded_name_ar:
      "%D8%A8%D9%8A%D8%AA%D8%B1%2807022%29%20%D9%82%D8%B5%D8%A7%D9%81%D8%A9%20%D8%A3%D8%B8%D8%A7%D9%81%D8%B1%20%28%D8%A7%D8%AE%D8%AA%D9%8A%D8%A7%D8%B1%20%D9%84%D9%88%D9%86%20%D8%B9%D8%B4%D9%88%D8%A7%D8%A6%D9%8A%29",
    featured: false,
    preorder: false,
    preorder_start_date: null,
    preorder_end_date: null,
    discount_start_date: null,
    discount_end_date: null,
    discount_max_per_period: null,
    discount_period_cycle_days: null,
    direct_discount: false,
    category: {
      id: 1079,
      name: "MOM & BABY",
      name_ar: "الأم والطفل",
      slug: "mom-baby",
      slug_ar: "",
      sub_categories: [
        {
          id: 1091,
          name: "GROOMING ESSENTIALS",
          name_ar: "مستلزمات العناية بالطفل",
          slug: "grooming-essentials",
          slug_ar: "",
        },
      ],
    },
    optional_category: null,
    in_stock: false,
    stock: 0,
    rate: "5.00",
    rate_count: 0,
    promotion: null,
    promotion_en: null,
    promotion_ar: null,
    is_favourite: false,
    is_compare: false,
    brand: {
      id: 8935,
      name: "Beter",
      name_ar: "بيتير",
      name_en: null,
      image:
        "https://cdn.supercommerce.io/tarshouby/uploads/Beter-1703101002.jpg",
      slug: "beter-1684311577",
      slug_ar: null,
    },
    payment_methods_discount_name_en: null,
    payment_methods_discount_name_ar: null,
    promos: [],
    product_variants_options: [],
    product_variants: [
      {
        id: 199782,
        name: "Beter (07022)Manicure Nail Clipper (Random Color Choice)",
        name_en: "Beter (07022)Manicure Nail Clipper (Random Color Choice)",
        name_ar: "بيتر(07022) قصافة أظافر (اختيار لون عشوائي)",
        sku: "138453",
        slug: "beter07022minicure-nail-clipper-ksaf-atfal",
        slug_ar: null,
        price: 362,
        discount_price: null,
        stock: 0,
        stock_alert: null,
        options: [],
        preorder: false,
        preorder_price: 0,
        value_ids: [],
        image:
          "https://cdn.supercommerce.io/tarshouby/uploads/138453-1762446936.jpg",
        alt: "Beter (07022)Manicure Nail Clipper (Random Color Choice)",
        alt_ar: "بيتر(07022) قصافة أظافر (اختيار لون عشوائي)",
        parent_id: 199781,
        images: [],
        in_stock: false,
        active: true,
        free_delivery: false,
        cart_step: 1,
        min_per_order: 0,
        promotion: null,
        promotion_en: null,
        promotion_ar: null,
        special_labels: null,
        special_labels_ar: null,
        special_labels_color: null,
        need_prescription: 0,
        step_unit_label_en: "Unit",
        step_unit_label_ar: "وحدة",
        step_package_label_en: "Package",
        step_package_label_ar: "علبة",
        enable_step_package: 0,
      },
    ],
    product_variants_count: 0,
    order: null,
    active: true,
    amount: 0,
    can_buy: null,
    soft_deleted: false,
    commission_amount: 0,
    affiliate_commission: null,
    variant_max_price: 0,
    exclusive_price: null,
    slug: "beter07022minicure-nail-clipper-ksaf-atfal",
    slug_ar: null,
    share_link:
      "https://alabdellatif-tarshouby.com/en/beter07022minicure-nail-clipper-ksaf-atfal",
    image:
      "https://cdn.supercommerce.io/tarshouby/uploads/138453-1762446936.jpg",
    alt: "Beter (07022)Manicure Nail Clipper (Random Color Choice)",
    alt_ar: "بيتر(07022) قصافة أظافر (اختيار لون عشوائي)",
    images: [],
    min_per_order: 0,
    max_per_order: null,
    type: 1,
    available_soon: false,
    price: 362,
    discount_price: null,
    preorder_price: 0,
    weight: "1.00",
    special_labels: null,
    special_labels_ar: null,
    special_labels_color: null,
    need_prescription: 0,
  },
];

export const products_2 = [
  {
    id: 207384,
    parent_id: 207383,
    sku: "140636",
    name: "Dermaelle Niacinamide Toner 350 ml",
    name_en: "Dermaelle Niacinamide Toner 350 ml",
    name_ar: "ديرما ايل نياسيناميد تونر 350 مل",
    encoded_name_en: "Dermaelle%20Niacinamide%20Toner%20350%20ml",
    encoded_name_ar:
      "%D8%AF%D9%8A%D8%B1%D9%85%D8%A7%20%D8%A7%D9%8A%D9%84%20%D9%86%D9%8A%D8%A7%D8%B3%D9%8A%D9%86%D8%A7%D9%85%D9%8A%D8%AF%20%D8%AA%D9%88%D9%86%D8%B1%20350%20%D9%85%D9%84",
    featured: false,
    preorder: false,
    preorder_start_date: null,
    preorder_end_date: null,
    discount_start_date: null,
    discount_end_date: null,
    discount_max_per_period: null,
    discount_period_cycle_days: null,
    direct_discount: false,
    category: {
      id: 1149,
      name: "SKIN CARE",
      name_ar: "العناية بالبشرة والجسم",
      slug: "skin-care",
      slug_ar: "",
      sub_categories: [
        {
          id: 1168,
          name: "TONERS",
          name_ar: "تونر",
          slug: "toners",
          slug_ar: null,
        },
      ],
    },
    optional_category: null,
    in_stock: false,
    stock: 0,
    rate: "5.00",
    rate_count: 0,
    promotion: null,
    promotion_en: null,
    promotion_ar: null,
    is_favourite: false,
    is_compare: false,
    brand: {
      id: 9236,
      name: "Derma elle",
      name_ar: "ديرما ايل",
      name_en: null,
      image:
        "https://cdn.supercommerce.io/tarshouby/uploads/Dermaelle-1725900509.jpg",
      slug: "derma elle",
      slug_ar: null,
    },
    payment_methods_discount_name_en: null,
    payment_methods_discount_name_ar: null,
    promos: [],
    product_variants_options: [],
    product_variants: [
      {
        id: 207384,
        name: "Dermaelle Niacinamide Toner 350 ml",
        name_en: "Dermaelle Niacinamide Toner 350 ml",
        name_ar: "ديرما ايل نياسيناميد تونر 350 مل",
        sku: "140636",
        slug: "dermaelleniacinamideradiance-toner350ml",
        slug_ar: null,
        price: 295,
        discount_price: null,
        stock: 0,
        stock_alert: null,
        options: [],
        preorder: false,
        preorder_price: 0,
        value_ids: [],
        image:
          "https://cdn.supercommerce.io/tarshouby/uploads/140636-1771339357.jpg",
        alt: "Dermaelle Niacinamide Toner 350 ml",
        alt_ar: "ديرما ايل نياسيناميد تونر 350 مل",
        parent_id: 207383,
        images: [],
        in_stock: false,
        active: true,
        free_delivery: false,
        cart_step: 1,
        min_per_order: 0,
        promotion: null,
        promotion_en: null,
        promotion_ar: null,
        special_labels: null,
        special_labels_ar: null,
        special_labels_color: null,
        need_prescription: 0,
        step_unit_label_en: "Unit",
        step_unit_label_ar: "وحدة",
        step_package_label_en: "Package",
        step_package_label_ar: "علبة",
        enable_step_package: 0,
      },
    ],
    product_variants_count: 0,
    order: null,
    active: true,
    amount: 0,
    can_buy: null,
    soft_deleted: false,
    commission_amount: 0,
    affiliate_commission: null,
    variant_max_price: 0,
    exclusive_price: null,
    slug: "dermaelleniacinamideradiance-toner350ml",
    slug_ar: null,
    share_link:
      "https://alabdellatif-tarshouby.com/en/dermaelleniacinamideradiance-toner350ml",
    image:
      "https://cdn.supercommerce.io/tarshouby/uploads/140636-1771339357.jpg",
    alt: "Dermaelle Niacinamide Toner 350 ml",
    alt_ar: "ديرما ايل نياسيناميد تونر 350 مل",
    images: [],
    min_per_order: 0,
    max_per_order: null,
    type: 1,
    available_soon: false,
    price: 295,
    discount_price: null,
    preorder_price: 0,
    weight: "1.00",
    special_labels: null,
    special_labels_ar: null,
    special_labels_color: null,
    need_prescription: 0,
  },
  {
    id: 207382,
    parent_id: 207381,
    sku: "140635",
    name: "Dermaelle Hyaluronic Acid Water 200 ml",
    name_en: "Dermaelle Hyaluronic Acid Water 200 ml",
    name_ar: "ديرما ايل ماء حمض الهيالورونيك 200 مل",
    encoded_name_en: "Dermaelle%20Hyaluronic%20Acid%20Water%20200%20ml",
    encoded_name_ar:
      "%D8%AF%D9%8A%D8%B1%D9%85%D8%A7%20%D8%A7%D9%8A%D9%84%20%D9%85%D8%A7%D8%A1%20%D8%AD%D9%85%D8%B6%20%D8%A7%D9%84%D9%87%D9%8A%D8%A7%D9%84%D9%88%D8%B1%D9%88%D9%86%D9%8A%D9%83%20200%20%D9%85%D9%84",
    featured: false,
    preorder: false,
    preorder_start_date: null,
    preorder_end_date: null,
    discount_start_date: null,
    discount_end_date: null,
    discount_max_per_period: null,
    discount_period_cycle_days: null,
    direct_discount: false,
    category: {
      id: 1149,
      name: "SKIN CARE",
      name_ar: "العناية بالبشرة والجسم",
      slug: "skin-care",
      slug_ar: "",
      sub_categories: [
        {
          id: 1169,
          name: "MOISTURIZERS",
          name_ar: "مرطب للبشرة",
          slug: "moisturizers",
          slug_ar: null,
        },
      ],
    },
    optional_category: null,
    in_stock: false,
    stock: 0,
    rate: "5.00",
    rate_count: 0,
    promotion: null,
    promotion_en: null,
    promotion_ar: null,
    is_favourite: false,
    is_compare: false,
    brand: {
      id: 9236,
      name: "Derma elle",
      name_ar: "ديرما ايل",
      name_en: null,
      image:
        "https://cdn.supercommerce.io/tarshouby/uploads/Dermaelle-1725900509.jpg",
      slug: "derma elle",
      slug_ar: null,
    },
    payment_methods_discount_name_en: null,
    payment_methods_discount_name_ar: null,
    promos: [],
    product_variants_options: [],
    product_variants: [
      {
        id: 207382,
        name: "Dermaelle Hyaluronic Acid Water 200 ml",
        name_en: "Dermaelle Hyaluronic Acid Water 200 ml",
        name_ar: "ديرما ايل ماء حمض الهيالورونيك 200 مل",
        sku: "140635",
        slug: "dermaelle-waterhyalu-acid200ml-gmyaa-anoaaa-albshr",
        slug_ar: null,
        price: 249,
        discount_price: null,
        stock: 0,
        stock_alert: null,
        options: [],
        preorder: false,
        preorder_price: 0,
        value_ids: [],
        image:
          "https://cdn.supercommerce.io/tarshouby/uploads/140635-1771338418.jpg",
        alt: "Dermaelle Hyaluronic Acid Water 200 ml",
        alt_ar: "ديرما ايل ماء حمض الهيالورونيك 200 مل",
        parent_id: 207381,
        images: [],
        in_stock: false,
        active: true,
        free_delivery: false,
        cart_step: 1,
        min_per_order: 0,
        promotion: null,
        promotion_en: null,
        promotion_ar: null,
        special_labels: null,
        special_labels_ar: null,
        special_labels_color: null,
        need_prescription: 0,
        step_unit_label_en: "Unit",
        step_unit_label_ar: "وحدة",
        step_package_label_en: "Package",
        step_package_label_ar: "علبة",
        enable_step_package: 0,
      },
    ],
    product_variants_count: 0,
    order: null,
    active: true,
    amount: 0,
    can_buy: null,
    soft_deleted: false,
    commission_amount: 0,
    affiliate_commission: null,
    variant_max_price: 0,
    exclusive_price: null,
    slug: "dermaelle-waterhyalu-acid200ml-gmyaa-anoaaa-albshr",
    slug_ar: null,
    share_link:
      "https://alabdellatif-tarshouby.com/en/dermaelle-waterhyalu-acid200ml-gmyaa-anoaaa-albshr",
    image:
      "https://cdn.supercommerce.io/tarshouby/uploads/140635-1771338418.jpg",
    alt: "Dermaelle Hyaluronic Acid Water 200 ml",
    alt_ar: "ديرما ايل ماء حمض الهيالورونيك 200 مل",
    images: [],
    min_per_order: 0,
    max_per_order: null,
    type: 1,
    available_soon: false,
    price: 249,
    discount_price: null,
    preorder_price: 0,
    weight: "1.00",
    special_labels: null,
    special_labels_ar: null,
    special_labels_color: null,
    need_prescription: 0,
  },
  {
    id: 207167,
    parent_id: 207166,
    sku: "140488",
    name: "Godrej Expert Rich Crème Hair Colour (4.16) Burgundy 20 gm +20 ml",
    name_en:
      "Godrej Expert Rich Crème Hair Colour (4.16) Burgundy 20 gm +20 ml",
    name_ar: "جودريج اكسبيرت ريتش كريم صبغة شعر(4.16) برغندي 20 جم+ 20 مل",
    encoded_name_en:
      "Godrej%20Expert%20Rich%20Cr%C3%A8me%20Hair%20Colour%20%284.16%29%20Burgundy%2020%20gm%20%2B20%20ml",
    encoded_name_ar:
      "%D8%AC%D9%88%D8%AF%D8%B1%D9%8A%D8%AC%20%D8%A7%D9%83%D8%B3%D8%A8%D9%8A%D8%B1%D8%AA%20%D8%B1%D9%8A%D8%AA%D8%B4%20%D9%83%D8%B1%D9%8A%D9%85%20%D8%B5%D8%A8%D8%BA%D8%A9%20%D8%B4%D8%B9%D8%B1%284.16%29%20%D8%A8%D8%B1%D8%BA%D9%86%D8%AF%D9%8A%2020%20%D8%AC%D9%85%2B%2020%20%D9%85%D9%84",
    featured: false,
    preorder: false,
    preorder_start_date: null,
    preorder_end_date: null,
    discount_start_date: null,
    discount_end_date: null,
    discount_max_per_period: null,
    discount_period_cycle_days: null,
    direct_discount: false,
    category: {
      id: 1185,
      name: "HAIR CARE",
      name_ar: "العناية بالشعر",
      slug: "hair-care",
      slug_ar: "",
      sub_categories: [
        {
          id: 1189,
          name: "NON-PERMANENT HAIR DYE",
          name_ar: "صبغة مؤقتة",
          slug: "non-permanent-hair-dye",
          slug_ar: null,
        },
      ],
    },
    optional_category: null,
    in_stock: false,
    stock: 0,
    rate: "2.00",
    rate_count: 0,
    promotion: null,
    promotion_en: null,
    promotion_ar: null,
    is_favourite: false,
    is_compare: false,
    brand: null,
    payment_methods_discount_name_en: null,
    payment_methods_discount_name_ar: null,
    promos: [],
    product_variants_options: [],
    product_variants: [
      {
        id: 207167,
        name: "Godrej Expert Rich Crème Hair Colour (4.16) Burgundy 20 gm +20 ml",
        name_en:
          "Godrej Expert Rich Crème Hair Colour (4.16) Burgundy 20 gm +20 ml",
        name_ar: "جودريج اكسبيرت ريتش كريم صبغة شعر(4.16) برغندي 20 جم+ 20 مل",
        sku: "140488",
        slug: "expert-rich416burgundy-henna20g20mborgondy-kys-1777562691",
        slug_ar: null,
        price: 57.9,
        discount_price: null,
        stock: 0,
        stock_alert: null,
        options: [],
        preorder: false,
        preorder_price: 0,
        value_ids: [],
        image:
          "https://cdn.supercommerce.io/tarshouby/uploads/140488-1771166061.png",
        alt: "Godrej Expert Rich Crème Hair Colour (4.16) Burgundy 20 gm +20 ml",
        alt_ar: "جودريج اكسبيرت ريتش كريم صبغة شعر(4.16) برغندي 20 جم+ 20 مل",
        parent_id: 207166,
        images: [],
        in_stock: false,
        active: true,
        free_delivery: false,
        cart_step: 1,
        min_per_order: 0,
        promotion: null,
        promotion_en: null,
        promotion_ar: null,
        special_labels: null,
        special_labels_ar: null,
        special_labels_color: null,
        need_prescription: 0,
        step_unit_label_en: "Unit",
        step_unit_label_ar: "وحدة",
        step_package_label_en: "Package",
        step_package_label_ar: "علبة",
        enable_step_package: 0,
      },
    ],
    product_variants_count: 0,
    order: null,
    active: true,
    amount: 0,
    can_buy: null,
    soft_deleted: false,
    commission_amount: 0,
    affiliate_commission: null,
    variant_max_price: 0,
    exclusive_price: null,
    slug: "expert-rich416burgundy-henna20g20mborgondy-kys-1777562691",
    slug_ar: null,
    share_link:
      "https://alabdellatif-tarshouby.com/en/expert-rich416burgundy-henna20g20mborgondy-kys-1777562691",
    image:
      "https://cdn.supercommerce.io/tarshouby/uploads/140488-1771166061.png",
    alt: "Godrej Expert Rich Crème Hair Colour (4.16) Burgundy 20 gm +20 ml",
    alt_ar: "جودريج اكسبيرت ريتش كريم صبغة شعر(4.16) برغندي 20 جم+ 20 مل",
    images: [],
    min_per_order: 0,
    max_per_order: 1,
    type: 1,
    available_soon: false,
    price: 57.9,
    discount_price: null,
    preorder_price: 0,
    weight: "1.00",
    special_labels: null,
    special_labels_ar: null,
    special_labels_color: null,
    need_prescription: 0,
  },
  {
    id: 207119,
    parent_id: 207118,
    sku: "140727",
    name: "Hepta Panthenol Hair Serum 100 ml",
    name_en: "Hepta Panthenol Hair Serum 100 ml",
    name_ar: "هيبتا بانثينول سيروم للشعر 100 مل",
    encoded_name_en: "Hepta%20Panthenol%20Hair%20Serum%20100%20ml",
    encoded_name_ar:
      "%D9%87%D9%8A%D8%A8%D8%AA%D8%A7%20%D8%A8%D8%A7%D9%86%D8%AB%D9%8A%D9%86%D9%88%D9%84%20%D8%B3%D9%8A%D8%B1%D9%88%D9%85%20%D9%84%D9%84%D8%B4%D8%B9%D8%B1%20100%20%D9%85%D9%84",
    featured: false,
    preorder: false,
    preorder_start_date: null,
    preorder_end_date: null,
    discount_start_date: null,
    discount_end_date: null,
    discount_max_per_period: null,
    discount_period_cycle_days: null,
    direct_discount: false,
    category: {
      id: 1185,
      name: "HAIR CARE",
      name_ar: "العناية بالشعر",
      slug: "hair-care",
      slug_ar: "",
      sub_categories: [
        {
          id: 1213,
          name: "SERUM",
          name_ar: "سيروم للشعر",
          slug: "serum",
          slug_ar: null,
        },
      ],
    },
    optional_category: null,
    in_stock: false,
    stock: 0,
    rate: "5.00",
    rate_count: 0,
    promotion: null,
    promotion_en: null,
    promotion_ar: null,
    is_favourite: false,
    is_compare: false,
    brand: null,
    payment_methods_discount_name_en: null,
    payment_methods_discount_name_ar: null,
    promos: [],
    product_variants_options: [],
    product_variants: [
      {
        id: 207119,
        name: "Hepta Panthenol Hair Serum 100 ml",
        name_en: "Hepta Panthenol Hair Serum 100 ml",
        name_ar: "هيبتا بانثينول سيروم للشعر 100 مل",
        sku: "140727",
        slug: "hepta-panthenol-hair-serum-100ml-b-1777562713",
        slug_ar: null,
        price: 250,
        discount_price: null,
        stock: 0,
        stock_alert: null,
        options: [],
        preorder: false,
        preorder_price: 0,
        value_ids: [],
        image:
          "https://cdn.supercommerce.io/tarshouby/uploads/140727-1771166823.jpg",
        alt: "Hepta Panthenol Hair Serum 100 ml",
        alt_ar: "هيبتا بانثينول سيروم للشعر 100 مل",
        parent_id: 207118,
        images: [],
        in_stock: false,
        active: true,
        free_delivery: false,
        cart_step: 1,
        min_per_order: 0,
        promotion: null,
        promotion_en: null,
        promotion_ar: null,
        special_labels: null,
        special_labels_ar: null,
        special_labels_color: null,
        need_prescription: 0,
        step_unit_label_en: "Unit",
        step_unit_label_ar: "وحدة",
        step_package_label_en: "Package",
        step_package_label_ar: "علبة",
        enable_step_package: 0,
      },
    ],
    product_variants_count: 0,
    order: null,
    active: true,
    amount: 0,
    can_buy: null,
    soft_deleted: false,
    commission_amount: 0,
    affiliate_commission: null,
    variant_max_price: 0,
    exclusive_price: null,
    slug: "hepta-panthenol-hair-serum-100ml-b-1777562713",
    slug_ar: null,
    share_link:
      "https://alabdellatif-tarshouby.com/en/hepta-panthenol-hair-serum-100ml-b-1777562713",
    image:
      "https://cdn.supercommerce.io/tarshouby/uploads/140727-1771166823.jpg",
    alt: "Hepta Panthenol Hair Serum 100 ml",
    alt_ar: "هيبتا بانثينول سيروم للشعر 100 مل",
    images: [],
    min_per_order: 0,
    max_per_order: 1,
    type: 1,
    available_soon: false,
    price: 250,
    discount_price: null,
    preorder_price: 0,
    weight: "1.00",
    special_labels: null,
    special_labels_ar: null,
    special_labels_color: null,
    need_prescription: 0,
  },
  {
    id: 206994,
    parent_id: 206993,
    sku: "140327",
    name: "NeoCell Beauty Builder 60 Gummies",
    name_en: "NeoCell Beauty Builder 60 Gummies",
    name_ar: "نيوسيل بيوتي بيلدر 60 قطعة مضغ",
    encoded_name_en: "NeoCell%20Beauty%20Builder%2060%20Gummies",
    encoded_name_ar:
      "%D9%86%D9%8A%D9%88%D8%B3%D9%8A%D9%84%20%D8%A8%D9%8A%D9%88%D8%AA%D9%8A%20%D8%A8%D9%8A%D9%84%D8%AF%D8%B1%2060%20%D9%82%D8%B7%D8%B9%D8%A9%20%D9%85%D8%B6%D8%BA",
    featured: false,
    preorder: false,
    preorder_start_date: null,
    preorder_end_date: null,
    discount_start_date: null,
    discount_end_date: null,
    discount_max_per_period: null,
    discount_period_cycle_days: null,
    direct_discount: false,
    category: {
      id: 1042,
      name: "VITAMINS & SUPPLEMENTS",
      name_ar: "الفيتامينات والمكملات الغذائية",
      slug: "vitamins-supplements",
      slug_ar: "",
      sub_categories: [
        {
          id: 1073,
          name: "HAIR, SKIN & NAILS",
          name_ar: "العناية بالبشرة والشعر والأظافر",
          slug: "hair-skin-nails",
          slug_ar: "",
        },
      ],
    },
    optional_category: null,
    in_stock: false,
    stock: 0,
    rate: "5.00",
    rate_count: 0,
    promotion: null,
    promotion_en: null,
    promotion_ar: null,
    is_favourite: false,
    is_compare: false,
    brand: {
      id: 9139,
      name: "Neocell",
      name_ar: "نيوسيل",
      name_en: null,
      image:
        "https://cdn.supercommerce.io/tarshouby/uploads/Neocell-1686760480.png",
      slug: "neocell",
      slug_ar: null,
    },
    payment_methods_discount_name_en: null,
    payment_methods_discount_name_ar: null,
    promos: [],
    product_variants_options: [],
    product_variants: [
      {
        id: 206994,
        name: "NeoCell Beauty Builder 60 Gummies",
        name_en: "NeoCell Beauty Builder 60 Gummies",
        name_ar: "نيوسيل بيوتي بيلدر 60 قطعة مضغ",
        sku: "140327",
        slug: "neocell-hair-skinnails-gummy-60-gumm",
        slug_ar: null,
        price: 1590,
        discount_price: null,
        stock: 0,
        stock_alert: null,
        options: [],
        preorder: false,
        preorder_price: 0,
        value_ids: [],
        image:
          "https://cdn.supercommerce.io/tarshouby/uploads/140327-1774793838.jpg",
        alt: "NeoCell Beauty Builder 60 Gummies",
        alt_ar: "نيوسيل بيوتي بيلدر 60 قطعة مضغ",
        parent_id: 206993,
        images: [],
        in_stock: false,
        active: true,
        free_delivery: false,
        cart_step: 1,
        min_per_order: 0,
        promotion: null,
        promotion_en: null,
        promotion_ar: null,
        special_labels: null,
        special_labels_ar: null,
        special_labels_color: null,
        need_prescription: 0,
        step_unit_label_en: "Unit",
        step_unit_label_ar: "وحدة",
        step_package_label_en: "Package",
        step_package_label_ar: "علبة",
        enable_step_package: 0,
      },
    ],
    product_variants_count: 0,
    order: null,
    active: true,
    amount: 0,
    can_buy: null,
    soft_deleted: false,
    commission_amount: 0,
    affiliate_commission: null,
    variant_max_price: 0,
    exclusive_price: null,
    slug: "neocell-hair-skinnails-gummy-60-gumm",
    slug_ar: null,
    share_link:
      "https://alabdellatif-tarshouby.com/en/neocell-hair-skinnails-gummy-60-gumm",
    image:
      "https://cdn.supercommerce.io/tarshouby/uploads/140327-1774793838.jpg",
    alt: "NeoCell Beauty Builder 60 Gummies",
    alt_ar: "نيوسيل بيوتي بيلدر 60 قطعة مضغ",
    images: [],
    min_per_order: 0,
    max_per_order: null,
    type: 1,
    available_soon: false,
    price: 1590,
    discount_price: null,
    preorder_price: 0,
    weight: "1.00",
    special_labels: null,
    special_labels_ar: null,
    special_labels_color: null,
    need_prescription: 0,
  },
  {
    id: 206900,
    parent_id: 206899,
    sku: "140353",
    name: "Mustbenda 100 mg 1 Vial",
    name_en: "Mustbenda 100 mg 1 Vial",
    name_ar: "موستبيندا 100 مجم 1 فيال",
    encoded_name_en: "Mustbenda%20100%20mg%201%20Vial",
    encoded_name_ar:
      "%D9%85%D9%88%D8%B3%D8%AA%D8%A8%D9%8A%D9%86%D8%AF%D8%A7%20100%20%D9%85%D8%AC%D9%85%201%20%D9%81%D9%8A%D8%A7%D9%84",
    featured: false,
    preorder: false,
    preorder_start_date: null,
    preorder_end_date: null,
    discount_start_date: null,
    discount_end_date: null,
    discount_max_per_period: null,
    discount_period_cycle_days: null,
    direct_discount: false,
    category: {
      id: 939,
      name: "MEDICATIONS",
      name_ar: "الأدوية",
      slug: "medications",
      slug_ar: "",
      sub_categories: [
        {
          id: 1035,
          name: "ANTI-NEOPLASTIC",
          name_ar: "مضاد للأورام",
          slug: "anti-neoplastic",
          slug_ar: "",
        },
      ],
    },
    optional_category: null,
    in_stock: false,
    stock: 0,
    rate: "5.00",
    rate_count: 0,
    promotion: null,
    promotion_en: null,
    promotion_ar: null,
    is_favourite: false,
    is_compare: false,
    brand: null,
    payment_methods_discount_name_en: null,
    payment_methods_discount_name_ar: null,
    promos: [],
    product_variants_options: [],
    product_variants: [
      {
        id: 206900,
        name: "Mustbenda 100 mg 1 Vial",
        name_en: "Mustbenda 100 mg 1 Vial",
        name_ar: "موستبيندا 100 مجم 1 فيال",
        sku: "140353",
        slug: "mustbenda-100-mg-1-vial-1777562682",
        slug_ar: null,
        price: 2046,
        discount_price: null,
        stock: 0,
        stock_alert: null,
        options: [],
        preorder: false,
        preorder_price: 0,
        value_ids: [],
        image:
          "https://cdn.supercommerce.io/tarshouby/uploads/NONE-1770842644.png",
        alt: "Mustbenda 100 mg 1 Vial",
        alt_ar: "موستبيندا 100 مجم 1 فيال",
        parent_id: 206899,
        images: [],
        in_stock: false,
        active: true,
        free_delivery: false,
        cart_step: 1,
        min_per_order: 0,
        promotion: null,
        promotion_en: null,
        promotion_ar: null,
        special_labels: null,
        special_labels_ar: null,
        special_labels_color: null,
        need_prescription: 0,
        step_unit_label_en: "Unit",
        step_unit_label_ar: "وحدة",
        step_package_label_en: "Package",
        step_package_label_ar: "علبة",
        enable_step_package: 0,
      },
    ],
    product_variants_count: 0,
    order: null,
    active: true,
    amount: 0,
    can_buy: null,
    soft_deleted: false,
    commission_amount: 0,
    affiliate_commission: null,
    variant_max_price: 0,
    exclusive_price: null,
    slug: "mustbenda-100-mg-1-vial-1777562682",
    slug_ar: null,
    share_link:
      "https://alabdellatif-tarshouby.com/en/mustbenda-100-mg-1-vial-1777562682",
    image: "https://cdn.supercommerce.io/tarshouby/uploads/NONE-1770842644.png",
    alt: "Mustbenda 100 mg 1 Vial",
    alt_ar: "موستبيندا 100 مجم 1 فيال",
    images: [],
    min_per_order: 0,
    max_per_order: 1,
    type: 1,
    available_soon: false,
    price: 2046,
    discount_price: null,
    preorder_price: 0,
    weight: "1.00",
    special_labels: null,
    special_labels_ar: null,
    special_labels_color: null,
    need_prescription: 0,
  },
  {
    id: 206779,
    parent_id: 206778,
    sku: "140339",
    name: "Aselia Life Sebo-Regulator Acne Prone Gel 50 gm",
    name_en: "Aselia Life Sebo-Regulator Acne Prone Gel 50 gm",
    name_ar: "أسيليا لايف جل للبشرة المعرضة للحبوب 50 جم",
    encoded_name_en:
      "Aselia%20Life%20Sebo-Regulator%20Acne%20Prone%20Gel%2050%20gm",
    encoded_name_ar:
      "%D8%A3%D8%B3%D9%8A%D9%84%D9%8A%D8%A7%20%D9%84%D8%A7%D9%8A%D9%81%20%D8%AC%D9%84%20%D9%84%D9%84%D8%A8%D8%B4%D8%B1%D8%A9%20%D8%A7%D9%84%D9%85%D8%B9%D8%B1%D8%B6%D8%A9%20%D9%84%D9%84%D8%AD%D8%A8%D9%88%D8%A8%2050%20%D8%AC%D9%85",
    featured: false,
    preorder: false,
    preorder_start_date: null,
    preorder_end_date: null,
    discount_start_date: null,
    discount_end_date: null,
    discount_max_per_period: null,
    discount_period_cycle_days: null,
    direct_discount: false,
    category: {
      id: 1149,
      name: "SKIN CARE",
      name_ar: "العناية بالبشرة والجسم",
      slug: "skin-care",
      slug_ar: "",
      sub_categories: [
        {
          id: 1176,
          name: "ACNE CARE",
          name_ar: "العناية بحب الشباب",
          slug: "acne-care",
          slug_ar: null,
        },
      ],
    },
    optional_category: null,
    in_stock: false,
    stock: 0,
    rate: "5.00",
    rate_count: 0,
    promotion: null,
    promotion_en: null,
    promotion_ar: null,
    is_favourite: false,
    is_compare: false,
    brand: {
      id: 8798,
      name: "Aselia",
      name_ar: "أسيليا",
      name_en: null,
      image:
        "https://cdn.supercommerce.io/tarshouby/uploads/Aselia-1703099396.jpg",
      slug: "aselia-1684311576",
      slug_ar: null,
    },
    payment_methods_discount_name_en: null,
    payment_methods_discount_name_ar: null,
    promos: [],
    product_variants_options: [],
    product_variants: [
      {
        id: 206779,
        name: "Aselia Life Sebo-Regulator Acne Prone Gel 50 gm",
        name_en: "Aselia Life Sebo-Regulator Acne Prone Gel 50 gm",
        name_ar: "أسيليا لايف جل للبشرة المعرضة للحبوب 50 جم",
        sku: "140339",
        slug: "aselia-life-gel-acne-prone-skin50gmha-1777562674",
        slug_ar: null,
        price: 200,
        discount_price: null,
        stock: 0,
        stock_alert: null,
        options: [],
        preorder: false,
        preorder_price: 0,
        value_ids: [],
        image:
          "https://cdn.supercommerce.io/tarshouby/uploads/140339-1770807657.jpg",
        alt: "Aselia Life Sebo-Regulator Acne Prone Gel 50 gm",
        alt_ar: "أسيليا لايف جل للبشرة المعرضة للحبوب 50 جم",
        parent_id: 206778,
        images: [],
        in_stock: false,
        active: true,
        free_delivery: false,
        cart_step: 1,
        min_per_order: 0,
        promotion: null,
        promotion_en: null,
        promotion_ar: null,
        special_labels: null,
        special_labels_ar: null,
        special_labels_color: null,
        need_prescription: 0,
        step_unit_label_en: "Unit",
        step_unit_label_ar: "وحدة",
        step_package_label_en: "Package",
        step_package_label_ar: "علبة",
        enable_step_package: 0,
      },
    ],
    product_variants_count: 0,
    order: null,
    active: true,
    amount: 0,
    can_buy: null,
    soft_deleted: false,
    commission_amount: 0,
    affiliate_commission: null,
    variant_max_price: 0,
    exclusive_price: null,
    slug: "aselia-life-gel-acne-prone-skin50gmha-1777562674",
    slug_ar: null,
    share_link:
      "https://alabdellatif-tarshouby.com/en/aselia-life-gel-acne-prone-skin50gmha-1777562674",
    image:
      "https://cdn.supercommerce.io/tarshouby/uploads/140339-1770807657.jpg",
    alt: "Aselia Life Sebo-Regulator Acne Prone Gel 50 gm",
    alt_ar: "أسيليا لايف جل للبشرة المعرضة للحبوب 50 جم",
    images: [],
    min_per_order: 0,
    max_per_order: null,
    type: 1,
    available_soon: false,
    price: 200,
    discount_price: null,
    preorder_price: 0,
    weight: "1.00",
    special_labels: null,
    special_labels_ar: null,
    special_labels_color: null,
    need_prescription: 0,
  },
  {
    id: 206690,
    parent_id: 206689,
    sku: "140474",
    name: "Ventamor Sunscreen Gel SPF 50+ 50 gm",
    name_en: "Ventamor Sunscreen Gel SPF 50+ 50 gm",
    name_ar: "فينتامور جل واقي شمس +SPF 50 50 جم",
    encoded_name_en: "Ventamor%20Sunscreen%20Gel%20SPF%2050%2B%2050%20gm",
    encoded_name_ar:
      "%D9%81%D9%8A%D9%86%D8%AA%D8%A7%D9%85%D9%88%D8%B1%20%D8%AC%D9%84%20%D9%88%D8%A7%D9%82%D9%8A%20%D8%B4%D9%85%D8%B3%20%2BSPF%2050%2050%20%D8%AC%D9%85",
    featured: false,
    preorder: false,
    preorder_start_date: null,
    preorder_end_date: null,
    discount_start_date: null,
    discount_end_date: null,
    discount_max_per_period: null,
    discount_period_cycle_days: null,
    direct_discount: false,
    category: {
      id: 1149,
      name: "SKIN CARE",
      name_ar: "العناية بالبشرة والجسم",
      slug: "skin-care",
      slug_ar: "",
      sub_categories: [
        {
          id: 1178,
          name: "OILY & COMBINED SKIN",
          name_ar: "البشرة الدهنية والمختلطة",
          slug: "oily-combined-skin",
          slug_ar: null,
        },
      ],
    },
    optional_category: null,
    in_stock: false,
    stock: 0,
    rate: "5.00",
    rate_count: 0,
    promotion: null,
    promotion_en: null,
    promotion_ar: null,
    is_favourite: false,
    is_compare: false,
    brand: null,
    payment_methods_discount_name_en: null,
    payment_methods_discount_name_ar: null,
    promos: [],
    product_variants_options: [],
    product_variants: [
      {
        id: 206690,
        name: "Ventamor Sunscreen Gel SPF 50+ 50 gm",
        name_en: "Ventamor Sunscreen Gel SPF 50+ 50 gm",
        name_ar: "فينتامور جل واقي شمس +SPF 50 50 جم",
        sku: "140474",
        slug: "ventamor-sunscreen-gel-50-ml-1777562690",
        slug_ar: null,
        price: 290,
        discount_price: null,
        stock: 0,
        stock_alert: null,
        options: [],
        preorder: false,
        preorder_price: 0,
        value_ids: [],
        image:
          "https://cdn.supercommerce.io/tarshouby/uploads/Ventamor-1771154162.jpg",
        alt: "Ventamor Sunscreen Gel SPF 50+ 50 gm",
        alt_ar: "فينتامور جل واقي شمس +SPF 50 50 جم",
        parent_id: 206689,
        images: [],
        in_stock: false,
        active: true,
        free_delivery: false,
        cart_step: 1,
        min_per_order: 0,
        promotion: null,
        promotion_en: null,
        promotion_ar: null,
        special_labels: null,
        special_labels_ar: null,
        special_labels_color: null,
        need_prescription: 0,
        step_unit_label_en: "Unit",
        step_unit_label_ar: "وحدة",
        step_package_label_en: "Package",
        step_package_label_ar: "علبة",
        enable_step_package: 0,
      },
    ],
    product_variants_count: 0,
    order: null,
    active: true,
    amount: 0,
    can_buy: null,
    soft_deleted: false,
    commission_amount: 0,
    affiliate_commission: null,
    variant_max_price: 0,
    exclusive_price: null,
    slug: "ventamor-sunscreen-gel-50-ml-1777562690",
    slug_ar: null,
    share_link:
      "https://alabdellatif-tarshouby.com/en/ventamor-sunscreen-gel-50-ml-1777562690",
    image:
      "https://cdn.supercommerce.io/tarshouby/uploads/Ventamor-1771154162.jpg",
    alt: "Ventamor Sunscreen Gel SPF 50+ 50 gm",
    alt_ar: "فينتامور جل واقي شمس +SPF 50 50 جم",
    images: [],
    min_per_order: 0,
    max_per_order: null,
    type: 1,
    available_soon: false,
    price: 290,
    discount_price: null,
    preorder_price: 0,
    weight: "1.00",
    special_labels: null,
    special_labels_ar: null,
    special_labels_color: null,
    need_prescription: 0,
  },
  {
    id: 206559,
    parent_id: 206558,
    sku: "140395",
    name: "Tresemmé Coconut & AloeVera Conditioner 400 ml (Discount 20%)",
    name_en: "Tresemmé Coconut & AloeVera Conditioner 400 ml (Discount 20%)",
    name_ar: "تريسمي بلسم الشعر جوز الهند & الالوفيرا 400 مل (خصم 20%)",
    encoded_name_en:
      "Tresemm%C3%A9%20Coconut%20%26%20AloeVera%20Conditioner%20400%20ml%20%28Discount%2020%25%29",
    encoded_name_ar:
      "%D8%AA%D8%B1%D9%8A%D8%B3%D9%85%D9%8A%20%D8%A8%D9%84%D8%B3%D9%85%20%D8%A7%D9%84%D8%B4%D8%B9%D8%B1%20%D8%AC%D9%88%D8%B2%20%D8%A7%D9%84%D9%87%D9%86%D8%AF%20%26%20%D8%A7%D9%84%D8%A7%D9%84%D9%88%D9%81%D9%8A%D8%B1%D8%A7%20400%20%D9%85%D9%84%20%28%D8%AE%D8%B5%D9%85%2020%25%29",
    featured: false,
    preorder: false,
    preorder_start_date: null,
    preorder_end_date: null,
    discount_start_date: null,
    discount_end_date: null,
    discount_max_per_period: null,
    discount_period_cycle_days: null,
    direct_discount: false,
    category: {
      id: 1112,
      name: "DAILY ESSENTIALS",
      name_ar: "العناية اليومية",
      slug: "daily-essentials",
      slug_ar: "",
      sub_categories: [
        {
          id: 1142,
          name: "SHAMPOO & CONDITIONER",
          name_ar: "شامبو وبلسم",
          slug: "shampoo-conditioner",
          slug_ar: null,
        },
      ],
    },
    optional_category: null,
    in_stock: false,
    stock: 0,
    rate: "5.00",
    rate_count: 0,
    promotion: null,
    promotion_en: null,
    promotion_ar: null,
    is_favourite: false,
    is_compare: false,
    brand: {
      id: 8905,
      name: "Tresemmé",
      name_ar: "تريسمي",
      name_en: null,
      image:
        "https://cdn.supercommerce.io/tarshouby/uploads/Tresemmé-1703100578.jpg",
      slug: "tresemme-1684311577",
      slug_ar: null,
    },
    payment_methods_discount_name_en: null,
    payment_methods_discount_name_ar: null,
    promos: [],
    product_variants_options: [],
    product_variants: [
      {
        id: 206559,
        name: "Tresemmé Coconut & AloeVera Conditioner 400 ml (Discount 20%)",
        name_en:
          "Tresemmé Coconut & AloeVera Conditioner 400 ml (Discount 20%)",
        name_ar: "تريسمي بلسم الشعر جوز الهند & الالوفيرا 400 مل (خصم 20%)",
        sku: "140395",
        slug: "tresemme-cond-cocoaloe400mlblsm-trtyb-khsm20",
        slug_ar: null,
        price: 168,
        discount_price: null,
        stock: 0,
        stock_alert: null,
        options: [],
        preorder: false,
        preorder_price: 0,
        value_ids: [],
        image:
          "https://cdn.supercommerce.io/tarshouby/uploads/140395-1770656156.png",
        alt: "Tresemmé Coconut & AloeVera Conditioner 400 ml (Discount 20%)",
        alt_ar: "تريسمي بلسم الشعر جوز الهند & الالوفيرا 400 مل (خصم 20%)",
        parent_id: 206558,
        images: [],
        in_stock: false,
        active: true,
        free_delivery: false,
        cart_step: 1,
        min_per_order: 0,
        promotion: null,
        promotion_en: null,
        promotion_ar: null,
        special_labels: null,
        special_labels_ar: null,
        special_labels_color: null,
        need_prescription: 0,
        step_unit_label_en: "Unit",
        step_unit_label_ar: "وحدة",
        step_package_label_en: "Package",
        step_package_label_ar: "علبة",
        enable_step_package: 0,
      },
    ],
    product_variants_count: 0,
    order: null,
    active: true,
    amount: 0,
    can_buy: null,
    soft_deleted: false,
    commission_amount: 0,
    affiliate_commission: null,
    variant_max_price: 0,
    exclusive_price: null,
    slug: "tresemme-cond-cocoaloe400mlblsm-trtyb-khsm20",
    slug_ar: null,
    share_link:
      "https://alabdellatif-tarshouby.com/en/tresemme-cond-cocoaloe400mlblsm-trtyb-khsm20",
    image:
      "https://cdn.supercommerce.io/tarshouby/uploads/140395-1770656156.png",
    alt: "Tresemmé Coconut & AloeVera Conditioner 400 ml (Discount 20%)",
    alt_ar: "تريسمي بلسم الشعر جوز الهند & الالوفيرا 400 مل (خصم 20%)",
    images: [],
    min_per_order: 0,
    max_per_order: null,
    type: 1,
    available_soon: false,
    price: 168,
    discount_price: null,
    preorder_price: 0,
    weight: "1.00",
    special_labels: null,
    special_labels_ar: null,
    special_labels_color: null,
    need_prescription: 0,
  },
  {
    id: 206474,
    parent_id: 206473,
    sku: "140298",
    name: "Melano Licorice & Hyaluronic Acid Serum 30 ml",
    name_en: "Melano Licorice & Hyaluronic Acid Serum 30 ml",
    name_ar: "ميلانو سيروم بالعرقسوس وحمض الهيالورونيك 30 مل",
    encoded_name_en:
      "Melano%20Licorice%20%26%20Hyaluronic%20Acid%20Serum%2030%20ml",
    encoded_name_ar:
      "%D9%85%D9%8A%D9%84%D8%A7%D9%86%D9%88%20%D8%B3%D9%8A%D8%B1%D9%88%D9%85%20%D8%A8%D8%A7%D9%84%D8%B9%D8%B1%D9%82%D8%B3%D9%88%D8%B3%20%D9%88%D8%AD%D9%85%D8%B6%20%D8%A7%D9%84%D9%87%D9%8A%D8%A7%D9%84%D9%88%D8%B1%D9%88%D9%86%D9%8A%D9%83%2030%20%D9%85%D9%84",
    featured: false,
    preorder: false,
    preorder_start_date: null,
    preorder_end_date: null,
    discount_start_date: null,
    discount_end_date: null,
    discount_max_per_period: null,
    discount_period_cycle_days: null,
    direct_discount: false,
    category: {
      id: 1149,
      name: "SKIN CARE",
      name_ar: "العناية بالبشرة والجسم",
      slug: "skin-care",
      slug_ar: "",
      sub_categories: [
        {
          id: 1170,
          name: "WHITENING",
          name_ar: "تفتيح البشرة",
          slug: "whitening",
          slug_ar: null,
        },
      ],
    },
    optional_category: {
      id: 1149,
      name: "SKIN CARE",
      name_ar: "العناية بالبشرة والجسم",
      slug: "skin-care",
      slug_ar: "",
      sub_categories: [
        {
          id: 1171,
          name: "ANTI-AGING",
          name_ar: "مضاد لعلامات تقدم السن",
          slug: "anti-aging",
          slug_ar: null,
        },
      ],
    },
    in_stock: false,
    stock: 0,
    rate: "5.00",
    rate_count: 0,
    promotion: null,
    promotion_en: null,
    promotion_ar: null,
    is_favourite: false,
    is_compare: false,
    brand: {
      id: 9205,
      name: "Melano Pharma",
      name_ar: "ميلانو فارما",
      name_en: null,
      image:
        "https://cdn.supercommerce.io/tarshouby/uploads/Melano%20Pharma-1716717375.jpg",
      slug: "melano pharma",
      slug_ar: null,
    },
    payment_methods_discount_name_en: null,
    payment_methods_discount_name_ar: null,
    promos: [],
    product_variants_options: [],
    product_variants: [
      {
        id: 206474,
        name: "Melano Licorice & Hyaluronic Acid Serum 30 ml",
        name_en: "Melano Licorice & Hyaluronic Acid Serum 30 ml",
        name_ar: "ميلانو سيروم بالعرقسوس وحمض الهيالورونيك 30 مل",
        sku: "140298",
        slug: "melano-skin-serum-liquorice30ml-aarksos",
        slug_ar: null,
        price: 380,
        discount_price: null,
        stock: 0,
        stock_alert: null,
        options: [],
        preorder: false,
        preorder_price: 0,
        value_ids: [],
        image:
          "https://cdn.supercommerce.io/tarshouby/uploads/140298-1770554619.jpg",
        alt: "Melano Licorice & Hyaluronic Acid Serum 30 ml",
        alt_ar: "ميلانو سيروم بالعرقسوس وحمض الهيالورونيك 30 مل",
        parent_id: 206473,
        images: [],
        in_stock: false,
        active: true,
        free_delivery: false,
        cart_step: 1,
        min_per_order: 0,
        promotion: null,
        promotion_en: null,
        promotion_ar: null,
        special_labels: null,
        special_labels_ar: null,
        special_labels_color: null,
        need_prescription: 0,
        step_unit_label_en: "Unit",
        step_unit_label_ar: "وحدة",
        step_package_label_en: "Package",
        step_package_label_ar: "علبة",
        enable_step_package: 0,
      },
    ],
    product_variants_count: 0,
    order: null,
    active: true,
    amount: 0,
    can_buy: null,
    soft_deleted: false,
    commission_amount: 0,
    affiliate_commission: null,
    variant_max_price: 0,
    exclusive_price: null,
    slug: "melano-skin-serum-liquorice30ml-aarksos",
    slug_ar: null,
    share_link:
      "https://alabdellatif-tarshouby.com/en/melano-skin-serum-liquorice30ml-aarksos",
    image:
      "https://cdn.supercommerce.io/tarshouby/uploads/140298-1770554619.jpg",
    alt: "Melano Licorice & Hyaluronic Acid Serum 30 ml",
    alt_ar: "ميلانو سيروم بالعرقسوس وحمض الهيالورونيك 30 مل",
    images: [],
    min_per_order: 0,
    max_per_order: null,
    type: 1,
    available_soon: false,
    price: 380,
    discount_price: null,
    preorder_price: 0,
    weight: "1.00",
    special_labels: null,
    special_labels_ar: null,
    special_labels_color: null,
    need_prescription: 0,
  },
];
