"""
Static categories for tokens used in validation and reordering.
"""

UNIT_TOKENS = {"mg", "mcg", "ml", "gm", "l", "kg", "iu", "cc"}

FORM_TOKENS = {
    "tab", "cap", "syrup", "cream", "ointment", "gel", "drops",
    "spray", "injectable", "supp", "sachet", "suspension",
    "solution", "eff", "infant", "powder", "lotion", "paste",
    "shampoo", "conditioner", "oil", "serum", "mask", "soap",
    "wash", "roll_on", "stick", "splash", "perfume", "cleanser",
    "mouthwash", "bottle", "liniment",
    "deodorant", "condom", "pads", "diapers", "wipes", "razor",
    "shower_gel", "toothpaste", "lip_balm", "antiseptic",
    "alcohol", "baby_bottle", "hair_dye",
    "scrub", "wax", "foam", "earbuds", "liquid", "air_freshener",
    "gloves", "jelly", "herbs", "foot_file", "cotton", "pumice",
    "toothpick", "clipper", "beard_wash", "micellar", "loofah",
    "toilet_paper", "underwear", "strips",
    "tweezers", "bath_foam", "aftershave", "shaving_foam",
    "oil_replacement", "douche", "sweetener", "stockings",
    "nursing_pads", "earplugs", "trimmer", "lenses", "trap",
    "compress", "plaster", "beard_oil", "cologne",
    "body_milk", "hair_restorer", "eyebrow_razor", "toilet_cover",
    "insecticide", "heel_rasp", "nail_polish_remover",
    "blue", "red", "green", "black", "white", "yellow",
    "pink", "purple", "orange", "brown", "grey", "gold", "silver", "beige",
    "scissors", "file", "sponge", "salt", "edp", "edt", "lotion",
    "body_butter", "whitening", "tampons", "eye_mask", "neck_pillow",
    "glue", "toothbrush", "mascara", "hardener", "lozenges",
    "hair_cream", "dental_floss", "glass_cleaner", "gargle",
    "sugar_wax", "tongue_cleaner", "panty_liners", "hand_wash",
    "body_splash", "body_spray", "body_mist", "shaving_gel",
    "navy", "jar", "sea", "bath", "peach", "orange",
    "blackheads", "remover", "handle", "berry", "vanilla",
    "oriental", "separator", "toes", "plugs", "cover", "pillow",
    "neck", "oud", "pomegranate", "sanitizer", "brush", "hair",
    "gum", "makeup", "chocolate", "strawberry", "mint", "lemon",
    "lavender", "jasmine", "aloe_vera",
    "feminine", "intimate", "double", "curved", "straight",
    "fiberglass", "sisal", "pedicure", "manicure", "heel",
    "beginners", "ergonomic", "economic", "hard", "complete",
    "activated", "cotton_candy", "blade", "shaving", "chrome",
    "edge", "ear", "diaper", "daily", "thick", "thin", "long",
    "cold", "wet", "baby", "maxi", "junior", "lips", "face",
    "body", "hands", "feet", "nails",
    "natural", "skin", "normal", "dry", "sensitive", "teeth",
    "antiperspirant", "sweat", "refreshing",
    "mosquito", "insects", "crawling", "flying", "killer",
    "repellent", "strip", "beard", "effervescent", "makhmaria",
    "family", "delka", "henna", "lice", "bonnet",
    "for_hair", "with_butter", "with_extract", "for_dandruff",
    "treatment", "plus", "head", "with_coconut", "shine", "argan",
    "nourishing", "repair", "shiny", "for_scalp", "moisturizing",
    "hyaluron", "protein", "with_protein", "softener", "smooth",
    "silky", "recipe", "swimming", "with_avocado", "snake", "pure",
    "organic", "onion", "castor", "rice", "fermented", "fermented_rice",
    "oil", "paris", "women", "for_women", "men", "for_men", "free",
    "beauty", "me", "go", "bio", "ultra", "number", "set",
    "mask", "addict", "on", "pert", "body", "semi", "dox", "to_repair",
    "scented", "di_lino", "avril", "keratin", "butter", "head",
    "shoulders", "protection", "professional", "colored", "oil_replacement",
    "blonde", "detangling", "herbal", "essences", "code", "piece",
    "permanent", "mist", "temporary", "rich", "soft", "long", "chestnut",
    "iron", "with_seeds", "with_charcoal", "detox", "volume", "dark",
    "with_extracts", "fruit", "with_shea", "with_berry", "with_apple",
    "bambusa", "for_nits", "nits", "ultra", "light", "very", "molecular",
    "for_restoring", "oval", "large", "small", "double", "action",
    "premier", "ever", "types", "curls", "rosemary", "for_strengthening",
    "for_protection", "style", "and_strengthening", "and_thickening",
    "hairburst", "strong", "salone", "plumpy", "nigella", "organica",
    "restorex", "chirosa", "brylcreem", "shifu", "tola_hair", "dona",
    "schwarzkopf", "palette", "modish", "premium", "wet_brush", "princess",
    "disney", "with_herbs",
    "size", "support", "device", "belt", "medium", "blood", "elastic",
    "scale", "knee", "wrist", "open", "measurement", "pressure", "bandage",
    "varicose", "dressing", "digital", "for_adults", "glucose", "plaster",
    "for_ankle", "for_knee", "adhesive", "glass", "supporter", "arm",
    "medical", "abdomen", "for_measuring", "ratio", "surgical", "fingers",
    "sport", "compression", "splint", "thermometer", "for_wrapping",
    "around", "holder", "patches", "wounds", "bottle", "cooling",
    "for_neck", "test", "check", "temperature", "massage", "straightening",
    "reading", "silk", "tiger", "washable", "thumb", "latex",
    "hydrocolloid", "age", "elderly", "cast", "stockings",
    "suspensory", "scrotal", "swabs", "bidet", "bleeding", "collar",
    "neck", "philadelphia", "underpads", "shoe", "finger", "drugs",
    "walker", "pelvis", "catheter", "insole", "pills", "column", "spinal",
    "stethoscope", "forehead", "for_thumb", "protector",
    "unisex", "incontinence", "lancet", "hemorrhoids", "tap",
}
